function onlyPlottingGUI(actinLen, mitoLen, numLastImg, extraPCol, mitoPerFile, widthRatioThresholdLow, widthRatioThresholdHigh, extraPName)
% Create figure
h.f = figure('units','pixels','position',[300,300,750,300],...
             'toolbar','none','menu','none');
% Create yes/no checkboxes
h.c(1) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,50,150,20],'string','Stripes plot');
h.c(2) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,100,150,20],'string','Extra parameter plots');  
h.c(3) = uicontrol('style','checkbox','units','pixels',...
                'position',[10,150,150,20],'string','Save figures');  
% Create numeric text boxes
txt1 = uicontrol('style','text','units','pixels',...
                'position',[250,70,200,20],'string','Mitochondria line profile width (µm)');
h.e(1) = uicontrol('style','edit','units','pixels',...
                'position',[250,50,200,20],'string',mitoLen);
txt2 = uicontrol('style','text','units','pixels',...
                'position',[250,120,200,20],'string','Actin line profile width (µm)');
h.e(2) = uicontrol('style','edit','units','pixels',...
                'position',[250,100,200,20],'string',actinLen);
txt3 = uicontrol('style','text','units','pixels',...
                'position',[250,170,200,20],'string','Number of the last image');
h.e(3) = uicontrol('style','edit','units','pixels',...
                'position',[250,150,200,20],'string',numLastImg);
txt4 = uicontrol('style','text','units','pixels',...
                'position',[250,220,200,20],'string','Column number of the extra parameter');
h.e(4) = uicontrol('style','edit','units','pixels',...
                'position',[250,200,200,20],'string',extraPCol);
txt5 = uicontrol('style','text','units','pixels',...
                'position',[500,120,200,20],'string','Mitochondria per file (maximum)');
h.e(5) = uicontrol('style','edit','units','pixels',...
                'position',[500,100,200,20],'string',mitoPerFile);
txt6 = uicontrol('style','text','units','pixels',...
                'position',[500,170,200,20],'string','Mitochondria width ratio threshold');
h.e(6) = uicontrol('style','edit','units','pixels',...
                'position',[500,150,200,20],'string',widthRatioThresholdLow);
txt7 = uicontrol('style','text','units','pixels',...
                'position',[500,220,200,20],'string','Mitochondria width ratio threshold');
h.e(7) = uicontrol('style','edit','units','pixels',...
                'position',[500,200,200,20],'string',widthRatioThresholdHigh);
% Create alpha text boxes            
txt8 = uicontrol('style','text','units','pixels',...
                'position',[500,70,200,20],'string','Name of extra parameters');             
h.e(8) = uicontrol('style','edit','units','pixels',...
               'position',[500,50,200,20],'string',extraPName);
% Create OK pushbutton   
h.p = uicontrol('style','pushbutton','units','pixels',...
                'position',[305,5,70,20],'string','Start plotting',...
                'callback',@p_call);
% Explanatory text about columns
txt8 = uicontrol('style','text','units','pixels',...
                'position',[10,250,200,100],'string','13 - Stripes, 14 - AIS, 15 - Small width, 16 - Mito>actin, 20 - Small area');              
            

    % Pushbutton callback
    function p_call(varargin)
        checks = get(h.c,'Value');
        vals = get(h.e,'String');
        save('checkboxes.mat','checks');
        save('edittextvals.mat','vals');
        close();
    end
end